apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: obb826rs6-nodejs
  janus-idp.io/tekton: obb826rs6-nodejs
  backstage.io/kubernetes-id: obb826rs6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: obb826rs6-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
